### ISSUE TITLE
add attachment subtext unreadable when using dark theme

### ISSUE THREAD

**Issue by lifegrain** [accrazed/YoRHA-UI-BetterDiscord#68]
## Brief summary

Add attachment popup has the option "upload a file", this option has a subtext which appears to be colored the same as the popup's background in the dark theme.\
This problem also occurs upon hovering the option, however due to color transition upon hovering the subtext are visible for a split second.

I did not check for light theme.

## Evidence

![image](https://github.com/accrazed/YoRHA-UI-BetterDiscord/assets/20505373/856b21db-b395-414f-a720-241e78637d59)
![image](https://github.com/accrazed/YoRHA-UI-BetterDiscord/assets/20505373/e3fbdcd7-82be-4c84-af1d-a339f62e713a)

## Additional Note

I apologize in advance if this problem is only on my side, based on my quick observation I don't think it is.\
If there any additional information required, I could be contacted through just replying in this issue.\
I will try to respond at the earliest time possible.

adding the following css, I was able to read the subtext.
```css
#channel-attach .colorDefault-2_rLdz .subtext-1mqKVB {
    color: var(--color-high);
}

#channel-attach .colorDefault-2_rLdz.focused-3LIdPu .subtext-1mqKVB {
    color: var(--color-muted);
}
```
